- hosts: my_host
  remote_user: my_host_user
  become: yes
  gather_facts: no

  tasks:
    - name: ensure apt cache is up to date
      apt: update_cache=yes
    - name: ensure packages are installed
      apt: name={{item}}
      with_items:
          - postgresql
          - libpq-dev
          - python-psycopg2

- hosts: my_host
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: realestate_dw
    dbuser: dw_user
    dbpassword: peeL9eehoh0rohceez9i

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ensure no other user can access the database
    postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
