- hosts: my_host
  remote_user: my_host_user
  gather_facts: no

  tasks:
    - name: 'Adding MongoDB APT Key'
      become: yes
      become_user: root
      become_method: sudo
      apt_key:
         keyserver: keyserver.ubuntu.com
         id: 9DA31620334BD75D9DCB49F368818C72E52529D4

    - name: 'Copying MongoDB repo list config to /etc/apt/sources.list.d/'
      become: yes
      become_user: root
      become_method: sudo
      copy:
        src: files/etc/apt/sources.list.d/mongodb-org-3.6.list
        dest: /etc/apt/sources.list.d/mongodb-org-3.6.list
        owner: root
        group: root
        mode: 0644

    - name: 'Updating APT cache'
      become: yes
      become_user: root
      become_method: sudo
      apt:
        update_cache: yes

    - name: 'Installing MongoDB-Org'
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: mongodb-org=3.6.5
        allow_unauthenticated: yes
